### ISSUE TITLE
"OSError: [Errno 12] Cannot allocate memory" on "tombo detect_modifications level_sample_compare"

### ISSUE THREAD

**Issue by stelmanAM** [nanoporetech/tombo#226]
I have picked up this a project part way through from a colleague doing nanopore sequencing. My understanding is that basecalling and demultiplexing have already been done. I was asked for assistance due to problems running `tombo detect_modifications level_sample_compare`

I ran resquigglling successfully using `tombo resquiggle --dna --processes 16 --num-most-common-errors 3 --overwrite Barcode2 ../dm3.fasta`

This is on a CentOS 6 machine with Python 3.6.8, 32 cores, 256G RAM and tombo v1.5. I have tried adjusting a number of parameters, including `--minimum-test-reads`, `--processes`, and `--multiprocess-region-size`, but keep getting memory allocation errors.

Wondering if you can shed some light. Complete trace below.

`$ tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 32 --statistics-file-basename level_comp_stats --multiprocess-region-size 1000`
[12:42:20] Parsing Tombo index file(s).
[12:42:24] Performing two-sample group comparison significance testing.
[12:42:24] Parsing Tombo index file(s).
[12:42:30] Calculating read coverage regions.
[12:42:30] Calculating read coverage.
[12:42:33] Calculating read coverage.
Traceback (most recent call last):
  File "/usr/local/bin/tombo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/tombo/__main__.py", line 242, in main
    tombo_stats._test_shifts_main(args)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 5013, in _test_shifts_main
    _level_samp_comp_main(args, reads_index)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4948, in _level_samp_comp_main
    ctrl_reads_index=ctrl_reads_index)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4581, in test_significance
    p.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by marcus1487** [comment]
I believe `--multiprocess-region-size` would be the most relevant parameter.

The other possibility here is that there are regions of very high coverage within the sample. Depending on the requirements of the study you might be able to downsample the reads selectively at higher coverage locations. This is enabled within tombo via the `tombo filters level_coverage` command ([docs here](https://nanoporetech.github.io/tombo/filtering.html#tombo-filter-level-coverage)). 

I would recommend visualizing the coverage in a genome browser using the browser_files output to determine if spikes in coverage might be the cause and when enough reads have been filtered ([see docs here](https://nanoporetech.github.io/tombo/text_output.html#tombo-text-output-browser-files)).

**Comment by stelmanAM** [comment]
Thanks for the quick reply. So far I tried `tombo filter level_coverage` with `--percent-to-filter` values increasing from 5, 10, and 25. I've also tried reducing `--multiprocess-region-size` from 1000, 500, 300, 100, & 10 (not really sure what minimum value is reasonable).

Now the error I'm getting is still memory related, but slightly different, such as:

`MemoryError: Unable to allocate 10.1 MiB for an array with shape (1323866,) and data type int64`
and
`MemoryError: Unable to allocate 187. MiB for an array with shape (24543385,) and data type int64`

See example trace below:

`$ tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 32 --statistics-file-basename level_comp_stats --multiprocess-region-size 100`
[13:49:06] Parsing Tombo index file(s).
[13:49:11] Performing two-sample group comparison significance testing.
[13:49:11] Parsing Tombo index file(s).
[13:49:17] Calculating read coverage regions.
[13:49:17] Calculating read coverage.
[13:49:19] Calculating read coverage.
Traceback (most recent call last):
  File "/usr/local/bin/tombo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/tombo/__main__.py", line 242, in main
    tombo_stats._test_shifts_main(args)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 5013, in _test_shifts_main
    _level_samp_comp_main(args, reads_index)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4948, in _level_samp_comp_main
    ctrl_reads_index=ctrl_reads_index)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4566, in test_significance
    1, region_size, ctrl_reads_index):
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_helper.py", line 1452, in iter_cov_regs
    ctrl_reads_index):
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_helper.py", line 1429, in iter_coverage_regions
    self._add_coverages(ctrl_reads_index))
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_helper.py", line 1404, in _add_coverages
    merged_cs_cov = ctrl_cs_cov.copy()
MemoryError: Unable to allocate 10.1 MiB for an array with shape (1323866,) and data type int64

**Comment by marcus1487** [comment]
This might be due to a very large genome. You might have some luck filtering by genomic region (using `tombo filter genome_locations`). If this works then you could loop over all contigs computing statistics on each one and then reverting the tombo index file and filtering for a new region. Let me know if this solves the memory issues on a small test at least.

**Comment by stelmanAM** [comment]
Would you expect the Drosophila dm3 genome to cause this type of problem?

I'll try your suggestion.

**Comment by stelmanAM** [comment]
I ran `tombo filter genome_locations --fast5-basedirs Barcode1 --include-regions chr2L` and `tombo filter genome_locations --fast5-basedirs Barcode2 --include-regions chr2L`

and am back to the original `OSError: [Errno 12] Cannot allocate memory` error message when running `tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 32 --statistics-file-basename level_comp_stats --multiprocess-region-size 100`

**Comment by marcus1487** [comment]
Can you try turning down the number of processes? It looks as though this memory error is occurring when the processes are spawned and thus copying the relevant information into each process.

**Comment by stelmanAM** [comment]
It seems to work with just one chromosome and just one processor. Fails even with 2 processors on single chromosome. Do I need more than 256G RAM, or is there a general problem with multiprocessors?

Single chromosome, single core estimated completion time is 8 hours. We're trying to figure out how to process this data faster.

**Comment by marcus1487** [comment]
Is the RAM very high for this single threaded run?

**Comment by marcus1487** [comment]
This is likely not a general problem with multiprocessors in general as the single threaded version actually uses the multiprocess interface still.

**Comment by stelmanAM** [comment]
Not high RAM for the single thread, but that was a good question to ask... it lead me to finding about 20 non-interactive orphan tombo processes still running from prior crashes that were taking up a lot of memory. Trying again now...

**Comment by stelmanAM** [comment]
I was now able to complete as follows:
`tombo filter level_coverage --fast5-basedirs Barcode1 --percent-to-filter 25`
`tombo filter level_coverage --fast5-basedirs Barcode2 --percent-to-filter 25`
`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 50 --processes 16 --statistics-file-basename level_comp_stats --multiprocess-region-size 100`

This took about 18 hours on 16 cores. However, when I subsequently attempted to plot, I got an empty stats file error:

`tombo plot most_significant --fast5-basedirs Barcode2 --control-fast5-basedirs Barcode1 --statistics-filename level_comp_stats.tombo.stats --pdf-filename Barcode1v2_most_significant_plot.pdf`

`[13:24:57] Loading statistics from file.`
`******************** ERROR ********************`
`        No locations identified. Most likely an empty statistics file.`

Similarly, when I tried to make a wig, I got an empty wig file with only a header:

`tombo text_output browser_files --statistics-filename level_comp_stats.tombo.stats --browser-file-basename level_compare_browserfile --file-types statistic`
`[13:27:21] Loading statistics from file.`
`[13:27:21] Parsing and outputting statistics wiggles.`

Not sure of the cause, I then tried to rerun detect_modifications with reduced `--minimum-test-reads 10`, but got the following errors, which I assume may be memory related?? Note that the first instance of the error occurred approx 6 hours into the run:

`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 10 --processes 16 --statistics-file-basename level_comp_stats --multiprocess-region-size 100`
[13:30:08] Parsing Tombo index file(s).
[13:30:14] Performing two-sample group comparison significance testing.
[13:30:14] Parsing Tombo index file(s).
[13:30:19] Calculating read coverage regions.
[13:30:19] Calculating read coverage.
[13:30:21] Calculating read coverage.
[13:31:32] Performing modified base detection across genomic regions.
 39%|████████████████████████████████▋                                                   | 1312172/3372306 [5:58:04<9:22:10, 61.08it/s]Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
 53%|████████████████████████████████████████████▋                                       | 1795992/3372306 [8:00:28<7:01:42, 62.30it/s]Process Process-12:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
 63%|████████████████████████████████████████████████████▊                               | 2119706/3372306 [9:24:10<5:33:23, 62.62it/s]Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
 83%|████████████████████████████████████████████████████████████████████▊              | 2796224/3372306 [12:12:17<2:30:52, 63.64it/s]Process Process-9:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
 93%|███████████████████████████████████████████████████████████████████████████████▎     | 3148056/3372306 [12:12:31<52:10, 71.63it/s]Process Process-15:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
 94%|███████████████████████████████████████████████████████████████████████████████▌     | 3159044/3372306 [12:12:31<49:27, 71.88it/s]Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4404, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4365, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate`
100%|████████████████████████████████████████████████████████████████████████████████████▉| 3372300/3372306 [12:12:39<00:00, 76.71it/s]

**Comment by stelmanAM** [comment]
Also, despite the error messages above, a stats file was created and I can generate wig data with `tombo text_output browser_files --statistics-filename level_comp_stats.tombo.stats --browser-file-basename level_compare_browserfile --file-types statistic`, but I get this error (perhaps expected given the above errors?) when running `tombo plot most_significant --fast5-basedirs Barcode2 --control-fast5-basedirs Barcode1 --statistics-filename level_comp_stats.tombo.stats --pdf-filename Barcode1v2_most_significant_plot.pdf`
[13:18:32] Loading statistics from file.
[13:18:32] Parsing Tombo index file(s).
[13:18:37] Parsing Tombo index file(s).
[13:18:43] Preparing plot data.
[13:19:01] Plotting.
Traceback (most recent call last):
  File "/usr/local/bin/tombo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/tombo/__main__.py", line 279, in main
    _plot_commands.plot_main(args)
  File "/usr/local/lib64/python3.6/site-packages/tombo/_plot_commands.py", line 2306, in plot_main
    plot_most_signif(*base_args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/_plot_commands.py", line 1993, in plot_most_signif
    title_include_chrm=False)
  File "/usr/local/lib64/python3.6/site-packages/tombo/_plot_commands.py", line 1378, in plot_two_samples
    _R_DF.rbind(SignalData1, SignalData2),
NameError: name '_R_DF' is not defined

**Comment by marcus1487** [comment]
For the zombie tombo processes, this is a known issue, but unfortunately I have not found a robust way to kill all tombo processes when a run fails.

For the errors you are seeing, I think these issues have been fixed in the development version. If you could install from github via `pip install git+https://github.com/nanoporetech/tombo/git` that should resolve the issue. Re-running from the detect_modifications step should resolve this issue. This is related to #224. I will try to get a new version posted to pip and conda soon.

For the detect_modified bases coverage threshold, I would recommend outputting the coverage wiggle file after the level_coverage filter to determine a reasonable value (should be relatively fast commands).

**Comment by marcus1487** [comment]
New version pushed to pypi and request made to update conda package.

**Comment by stelmanAM** [comment]
Hi Marcus,

version 1.5.1 solves the plot issues, but I still get multiple occurances of the following error:

`tombo detect_modifications level_sample_compare --fast5-basedirs Barcode2 --alternate-fast5-basedirs Barcode1 --minimum-test-reads 10 --processes 16 --statistics-file-basename level_comp_stats --multiprocess-region-size 100`
[17:07:44] Parsing Tombo index file(s).
[17:07:49] Performing two-sample group comparison significance testing.
[17:07:49] Parsing Tombo index file(s).
[17:07:54] Calculating read coverage regions.
[17:07:54] Calculating read coverage.
[17:07:56] Calculating read coverage.
[17:09:06] Performing modified base detection across genomic regions.
  5%|████▏                                                                               | 169067/3372306 [1:18:19<24:44:00, 35.98it/s]Process Process-16:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4424, in _test_signif_worker
    stat_type)
  File "/usr/local/lib64/python3.6/site-packages/tombo/tombo_stats.py", line 4385, in compute_group_reg_stats
    np.concatenate(reg_stats), np.concatenate(reg_poss),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by marcus1487** [comment]
I think this might be due to a weird edge condition brought on by the small `--multiprocess-region-size` value. I'll try to push a fix for this issue shortly.

**Comment by marcus1487** [comment]
I just pushed a commit that will hopefully address this issue. Could reinstall from github and re-run this command to confirm?

**Comment by stelmanAM** [comment]
That seemed to work without the error messages this time.
